# .base: &base
#   {}  # Base config, like: `image_name`, `tag_name`
# .run_options: &run_options
#   {} # Docker run options, like: `p`, `publish`, `v`, `volume`
# .run_args: &run_args
#   {} #Docker run args, like: `character-set-server`
#
# latest:
#   base:
#     <<: *base
#   run_options:
#     <<: *run_options
#   run_args:
#     <<: *run_args
#
# tag1:
#   base:
#     <<: *base
#   run_options:
#     <<: *run_options
#   run_args:
#     <<: *run_args
#
# tag2:
#   base:
#     <<: *base
#   run_options:
#     <<: *run_options
#   run_args:
#     <<: *run_args
